export const COMMUNITY_ITEMS = [
  {
    id: 1,
    tag: 'Tips',
    title: '5 mẹo chọn sân gần bạn (giá hợp lý)',
    excerpt: 'Cách đọc rating, so sánh tiện ích và tránh giờ cao điểm để tiết kiệm chi phí.',
    author: 'SanSieuToc Team',
    time: '2h ago',
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=60',
    imageAlt: 'Football field',
    content:
      'Cách đọc rating, so sánh tiện ích và tránh giờ cao điểm để tiết kiệm chi phí.\n\nGợi ý nhanh: ưu tiên sân có đánh giá ổn định, xem kỹ tiện ích (đèn, bãi xe, phòng tắm), và đặt trước để tránh khung giờ cao điểm.',
  },
  {
    id: 2,
    tag: 'Match',
    title: 'Tìm đội đá giao hữu tối thứ 6',
    excerpt: 'Khu vực TP.HCM, trình độ trung bình khá. Cần 3-4 bạn.',
    author: 'Minh Nguyen',
    time: '6h ago',
    image: 'https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=1200&q=60',
    imageAlt: 'Players on field',
    content:
      'Khu vực TP.HCM, trình độ trung bình khá. Cần 3-4 bạn.\n\nNhắn tin để chốt kèo: khu vực, giờ đá, số người hiện có và mức phí dự kiến.',
  },
  {
    id: 3,
    tag: 'Review',
    title: 'Review sân D7: đèn sáng, cỏ ổn',
    excerpt: 'Điểm cộng: dễ đậu xe, có nước. Điểm trừ: hơi đông giờ 20-22h.',
    author: 'Khanh Le',
    time: '1d ago',
    image: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=1200&q=60',
    imageAlt: 'Stadium lights',
    content:
      'Điểm cộng: dễ đậu xe, có nước. Điểm trừ: hơi đông giờ 20-22h.\n\nNếu đá giờ cao điểm nên đặt sớm; đi sớm 10-15 phút để khởi động và check-in.',
  },
  {
    id: 4,
    tag: 'Owner',
    title: 'Chia sẻ cách set giá theo khung giờ',
    excerpt: 'Gợi ý set giá theo demand + combo khuyến mãi để tăng doanh thu.',
    author: 'Owner Club',
    time: '2d ago',
    image: 'https://images.unsplash.com/photo-1526232373132-0e4ee16f4b38?auto=format&fit=crop&w=1200&q=60',
    imageAlt: 'Football pitch',
    content:
      'Gợi ý set giá theo demand + combo khuyến mãi để tăng doanh thu.\n\nCó thể chia 3 mức: thấp điểm / trung bình / cao điểm, kèm voucher giới hạn cho giờ khó lấp.',
  },
  {
    id: 5,
    tag: 'Tips',
    title: 'Checklist trước khi ra sân',
    excerpt: 'Giày, băng gối, nước uống, áo bib và cách khởi động 5 phút.',
    author: 'Coach Tran',
    time: '3d ago',
    image: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?auto=format&fit=crop&w=1200&q=60',
    imageAlt: 'Football shoes',
    content:
      'Giày, băng gối, nước uống, áo bib và cách khởi động 5 phút.\n\nĐừng quên cooldown nhẹ 3-5 phút sau trận để giảm đau mỏi.',
  },
  {
    id: 6,
    tag: 'Match',
    title: 'Kèo sân 11: cần thêm 6 người',
    excerpt: 'Ha Noi, CN tuần này. Vào sân đúng giờ, chia team random.',
    author: 'Duc Pham',
    time: '4d ago',
    image: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1200&q=60',
    imageAlt: 'Football game',
    content:
      'Ha Noi, CN tuần này. Vào sân đúng giờ, chia team random.\n\nAi tham gia để lại số lượng người + vị trí chơi để sắp team cân bằng.',
  },
  {
    id: 7,
    tag: 'Review',
    title: 'Sân mini Lê Duẩn: nhỏ nhưng sạch',
    excerpt: 'Phù hợp đá 5, mặt sân đều. Nhà tắm ổn, wifi hơi yếu.',
    author: 'Thanh Vu',
    time: '5d ago',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=60',
    imageAlt: 'Mini pitch',
    content:
      'Phù hợp đá 5, mặt sân đều. Nhà tắm ổn, wifi hơi yếu.\n\nNên mang theo nước cá nhân nếu đá khung giờ nắng.',
  },
  {
    id: 8,
    tag: 'Owner',
    title: 'Khuyến mãi: làm sao không lỗ?',
    excerpt: 'Tính cost/slot + giới hạn voucher theo khung giờ để tối ưu.',
    author: 'Marketing',
    time: '6d ago',
    image: 'https://images.unsplash.com/photo-1520975916090-3105956dac38?auto=format&fit=crop&w=1200&q=60',
    imageAlt: 'Promotion',
    content:
      'Tính cost/slot + giới hạn voucher theo khung giờ để tối ưu.\n\nGợi ý: đặt ngưỡng số lượng voucher/ngày và chỉ áp dụng cho giờ thấp điểm.',
  },
  {
    id: 9,
    tag: 'Tips',
    title: 'Đá ban đêm: cách giảm chấn thương',
    excerpt: 'Warm-up kỹ hơn, chọn giày đinh phù hợp và đừng bỏ qua cooldown.',
    author: 'Physio',
    time: '1w ago',
    image: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=1200&q=60',
    imageAlt: 'Night field',
    content:
      'Warm-up kỹ hơn, chọn giày đinh phù hợp và đừng bỏ qua cooldown.\n\nĐặc biệt lưu ý mặt sân trơn/ướt và giảm tốc khi đổi hướng.',
  },
  {
    id: 10,
    tag: 'Match',
    title: 'Tìm đội đá 7 người (kèo đều)',
    excerpt: 'TP.HCM, tối T3. Ưu tiên chơi đẹp, không va chạm.',
    author: 'Huy',
    time: '1w ago',
    image: 'https://images.unsplash.com/photo-1471295253337-3ceaaedca402?auto=format&fit=crop&w=1200&q=60',
    imageAlt: 'Team match',
    content:
      'TP.HCM, tối T3. Ưu tiên chơi đẹp, không va chạm.\n\nCần đủ người sẽ chốt sân và chia phí theo đầu người.',
  },
  {
    id: 11,
    tag: 'Review',
    title: 'Celadon City: dịch vụ tốt, giá ok',
    excerpt: 'Bãi xe rộng, đèn sáng, nhân viên support nhanh.',
    author: 'Linh',
    time: '2w ago',
    image: 'https://images.unsplash.com/photo-1547347298-4074fc3086f0?auto=format&fit=crop&w=1200&q=60',
    imageAlt: 'Stadium',
    content:
      'Bãi xe rộng, đèn sáng, nhân viên support nhanh.\n\nĐiểm phù hợp: nhóm đá định kỳ cần sân ổn định, dịch vụ hỗ trợ tốt.',
  },
  {
    id: 12,
    tag: 'Owner',
    title: 'Tối ưu lịch sân bằng slot 90 phút',
    excerpt: 'Gộp slot để giảm thời gian trống và tăng tỷ lệ lấp đầy.',
    author: 'Ops',
    time: '2w ago',
    image: 'https://images.unsplash.com/photo-1520975958225-457d2c611a0a?auto=format&fit=crop&w=1200&q=60',
    imageAlt: 'Planning',
    content:
      'Gộp slot để giảm thời gian trống và tăng tỷ lệ lấp đầy.\n\nKết hợp chính sách đặt cọc để giảm hủy giờ phút chót.',
  },
];
